""" creates cinema_datas table

Revision ID: 50dcc3c95ffd
Revises: 639a8b9f298d
Create Date: 2022-08-14 10:45:36.227654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50dcc3c95ffd'
down_revision = '639a8b9f298d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.Column('province', sa.String(length=200), nullable=True),
    sa.Column('total_screens', sa.Integer(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('total_INCAA_spaces', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema_datas')
    # ### end Alembic commands ###
