"""empty message

Revision ID: 639a8b9f298d
Revises: fad54e4d299b
Create Date: 2022-08-13 23:27:37.275063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639a8b9f298d'
down_revision = 'fad54e4d299b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('buildings', sa.Column('load_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'load_date')
    op.drop_table('totals')
    # ### end Alembic commands ###
